name: Apply Repository Settings

on:
  workflow_dispatch:

jobs:
  apply-settings:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          repository: sociail/.github
          token: ${{ secrets.MSUALP_TOKEN }}

      - name: Show Git config
        run: git config --global --list

      - name: Fetch Upstream Repo
        run: |
          echo "Adding tmp_upstream ${UPSTREAM_REPO}"
          git remote add tmp_upstream $UPSTREAM_REPO
          echo "Fetching tmp_upstream"
          git -c http.extraheader="AUTHORIZATION: bearer ${{ secrets.MSUALP_TOKEN }}" fetch tmp_upstream
        env:
          UPSTREAM_REPO: https://github.com/sociail/.github.git
