name: Apply Repository Settings to Current Repo

on:
  workflow_dispatch:

jobs:
  apply-settings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: sociail/.github
          token: ${{ secrets.MSUALP_TOKEN }}

      - name: Configure Git Authentication
        run: |
          git config --global http.https://github.com/.extraheader "AUTHORIZATION: Basic $(echo -n ${GITHUB_ACTOR}:${{ secrets.MSUALP_TOKEN }} | base64 --wrap=0)"

      - name: Show Git config
        run: git config --global --list

      - name: Fetch Upstream Repo
        run: |
          echo "Adding tmp_upstream ${UPSTREAM_REPO}"
          git remote add tmp_upstream $UPSTREAM_REPO
          echo "Fetching tmp_upstream"
          git fetch tmp_upstream
        env:
          UPSTREAM_REPO: https://github.com/sociail/.github.git
