name: Apply Repository Settings to Current Repo

on:
  push:
    branches:
      - dev
    paths:
      - 'settings/settings.yml'  # Specify the path to the settings.yml file
  workflow_dispatch:

jobs:
  apply-settings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Configure Git Authentication
        run: |
          git config --global http.https://github.com/.extraheader "AUTHORIZATION: basic $(echo -n x-access-token:${{ secrets.MSUALP_TOKEN }} | base64 --wrap=0)"

      - name: Apply settings to repositories
        uses: repo-sync/github-sync@v2
        with:
          source_repo: "https://github.com/sociail/.github.git"
          github_token: ${{ secrets.MSUALP_TOKEN }}
