name: Apply Repository Settings

on:
  workflow_dispatch:

jobs:
  apply-settings:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          repository: .github
          token: ${{ secrets.MSUALP_TOKEN }}

      - name: Show Git config
        run: git config --global --list

      - name: Fetch Upstream Repo
        run: |
          echo "Fetching upstream repo"
          git fetch origin
        working-directory: .github
